# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd8c56d301cb5a0496536243faa217b80770f4a77b14bb12da439da0c681646dc5fab26e67817436534921bec5fd2fb692c4eeb3f2717ed91c4a75150f825644

test:
  secret_key_base: c8c0e65e0261ae42b0f654bb84d3cce325f1b2c61910af8b83c8db6c76f523ac8dbed612a7aa7a767c484885a9a900e787e45846714f0dad379aa5fde9167b60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
